# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run Scraper - Update data # 워크플로우 이름 지정

on:
  push:
      branches: [master]
  # schedule:
  #   - cron:  '*/20 * * * *' # 주기적으로 실행하기 위한 스케줄링 - cron 설정
jobs:
  build:

    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        # python-version: ${{ matrix.python-version }}
        python-version: '3.x'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pwd
        ls -al
        pip install -r requirements.txt
    - name: Run Scraper with python
      run: |
        echo "before run scraping.py"
        python3 "scraping.py"
        echo "after run scraping.py"
    - name: Commits
      run: |
        # git config --local user.email "gsafe1213@gmail.com"
        # git config --local user.name "update news" # 커밋에 포함될 이름
        git add news.json
        git commit -m "Auto - Update data with Scraping" # 커밋 메세지
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'master'
        github_token: $ 
